from tool_context_relay.agent.pretty import emit_default

SMALL_PAGE_URL = "https://demo.local/summary"
LARGE_PAGE_URL = "https://demo.local/history"

_SMALL_PAGE_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Demo Small Page</title>
</head>
<body>
  <h1>Small Demo</h1>
  <p>This is a tiny demo page with just a few words.</p>
</body>
</html>
"""

_LARGE_PAGE_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Demo Large Page</title>
</head>
<body>
  <h1>Large Demo</h1>
  <p>This page is intentionally larger to exercise boxing behavior.</p>
  <img src="images/desk.jpg" alt="A desk image that adds to the page size." />
  <section>
    <h2>Overview</h2>
    <p>We repeat structured content to increase the payload size.</p>
  </section>
  {sections}
  <img src="images/cat.png" alt="A cute cat image that adds to the page size." />
  <footer>Generated by demo.local/large</footer>
</body>
</html>
"""


def _build_large_sections() -> str:
    blocks: list[str] = []
    for idx in range(1, 13):
        blocks.append(
            """<section>
  <h2>Section {idx}</h2>
  <p>Content block {idx} repeats to keep the output deterministic.</p>
  <p>Additional details for section {idx} help push the size over the boxing limit.</p>
</section>""".format(
                idx=idx
            )
        )
    return "\n".join(blocks)


def fun_get_page(url: str) -> str:
    """Return an HTML page for a simulated URL.

    Args:
        url (str): The URL to fetch.
    Returns:
        str: The HTML page contents.
    """
    if url == SMALL_PAGE_URL:
        page = _SMALL_PAGE_HTML
    elif url == LARGE_PAGE_URL:
        page = _LARGE_PAGE_HTML.format(sections=_build_large_sections())
    else:
        page = (
            "<!doctype html>\n"
            "<html lang=\"en\">\n"
            "<head><meta charset=\"utf-8\" /><title>Demo Not Found</title></head>\n"
            "<body><h1>Unknown URL</h1><p>No content for this URL.</p></body>\n"
            "</html>\n"
        )

    emit_default(
        f"Simulated page fetch. url={url!r}, length={len(page)}",
        group=fun_get_page.__name__,
    )
    return page
